<a href="https://colab.research.google.com/github/Swathi04705/Applied_Linear_Algebra/blob/main/ALA2_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a = np.array([1,2,3])
assert(a.dtype == np.int64)

#shape of a?
assert(a.shape == (1+2,))
a.shape

(3,)

In [2]:
a


array([1, 2, 3])

In [3]:
a.T

array([1, 2, 3])

In [ ]:
x=[1,2,3]
x==[1,2,3]

In [5]:
a = np.zeros(4)
assert a == [0, 0, 0, 0]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [6]:
a==[0,0,0,0]

array([ True,  True,  True,  True])

In [7]:
np.array_equal(a,[0,0,0,0])

True

In [8]:
np.array_equal(a,[1,2,3])

False

In [9]:
np.array_equal(x,[0,0,0,0])

False

In [10]:
np.array_equal(x,[1,2,3])

True

In [11]:
(a==[1,2,3,4]).all()

np.False_

In [12]:
(a==[0,0,0,0]).all()

np.True_